# Container Image
quarkus.container-image.build=true
quarkus.container-image.group=bastianelli-mic
quarkus.container-image.name=watchlog
quarkus.container-image.tag=1.0.0-SNAPSHOT

# Reactive PostgreSQL Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=watchlog
quarkus.datasource.password=watchlog
quarkus.datasource.reactive.url=postgresql://localhost:5432/watchlog

# Hibernate Reactive
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
