quarkus.container-image.build=true
quarkus.container-image.group=bastianelli-mic
quarkus.container-image.name=watchlog
quarkus.container-image.tag=1.0.0-SNAPSHOT

# Reactive PostgreSQL
quarkus.datasource.jdbc=false
quarkus.reactive.url=postgresql://localhost:5432/quarkus_test
quarkus.reactive.username=quarkus_test
quarkus.reactive.password=quarkus_test

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
